#define CONSTANTE_H
#define D 1
#define W 0

//PIN ROBOT
#define MOTORPIN1 8 
#define MOTORPIN2 7
#define ENABLEPIN1 9 
#define MOTORPIN3 6
#define MOTORPIN4 5
#define ENABLEPIN2 4

//Pin sonor
#define TRIG_PIN 13
#define ECHO_PIN 12

//Pin Sensors
#define LEFT_PHOTOELECTRIQUE_PIN 17
#define MIDDLE_LEFT_PHOTOELECTRIQUE_PIN 16
#define MIDDLE_RIGHT_PHOTOELECTRIQUE_PIN 15
#define RIGHT_PHOTOELECTRIQUE_PIN 14

//Pin RFID
#define SS_PIN 53
#define RST_PIN 22
